jobs:
  recursive: recursive1;
  inorder: |
      loop1 ? loop2; @monitor1 @monitor2
      loop2;
      loop3;
  concurrent: |
      [
        loop1 ? loop2;
        loop3;
      ]
  concurrentAndThenInorder: |
      [
        loop1 ? loop2 : loop1;
        loop2 ? loop3;
      ]
      loop1;
      loop2;

processes:
  recursive1:
    cwd: /Users/jaredgorski
    command: |
      for i in {1..5}
      do
        sleep 1
        echo "Recursive1 $i"
      done
    onsucceed: recursive2
  recursive2:
    cwd: /Users/jaredgorski
    command: |
      for i in {1..5}
      do
        sleep 1
        echo "Recursive2 $i"
      done
    onsucceed: recursive1
  loop1:
    cwd: /Users/jaredgorski
    command: |
      for i in {1..5}
      do
        sleep 1
        echo "Loop1 $i"
      done
  loop2:
    cwd: /Users/jaredgorski
    command: |
      for i in {1..3}
      do
        sleep 1
        echo "Loop2 $i"
      done
      exit
  loop3:
    cwd: /Users/jaredgorski
    command: |
      for i in {1..5}
      do
        sleep 1
        echo "Loop3 $i"
      done

log_monitors:
  monitor1:
    buffer_size: 15
    ontrigger: loop2
    test: |
      grep "Loop1 3" <<< "$ARPX_BUFFER"
  monitor2:
    buffer_size: 15
    ontrigger: loop3
    test: |
      grep "Loop1 5" <<< "$ARPX_BUFFER"
