[package]
name = "pmux"
description = "Utility for running and automating concurrent processes"
version = "0.0.1"
license = "MIT"
readme = "README.md"
keywords = ["automation", "process", "task", "multiplexer"]
authors = ["Jared Gorski <jaredgorski6@gmail.com>"]
repository = "https://github.com/jaredgorski/pmux"
edition = "2018"

[badges]
travis-ci = { repository = "jaredgorski/pmux" }

[[bin]]
name = "pmux"
path = "src/main.rs"
doc = false

[dependencies]
crossbeam-channel = "0.3"
dirs = "2.0"
serde = { version = "1.0.99", features = ["derive"] }
serde_yaml = "0.8.9"
