[package]
name = "tom"
version = "0.1.0"
authors = ["jaredgorski <jared.gorski@liferay.cloud>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "2.0"
serde = { version = "1.0.99", features = ["derive"] }
serde_yaml = "0.8.9"
