[package]
name = "tom"
description = "Utility for automating basic processes"
version = "0.1.0"
license = "MIT"
readme = "README.md"
keywords = ["automation", "process", "process-manager"]
authors = ["Jared Gorski <jaredgorski6@gmail.com>"]
repository = "https://github.com/jaredgorski/tom"
edition = "2018"

[badges]
travis-ci = { repository = "jaredgorski/tom" }

[[bin]]
doc = false
path = "src/main.rs"
name = "tom"

[dependencies]
dirs = "2.0"
serde = { version = "1.0.99", features = ["derive"] }
serde_yaml = "0.8.9"
